version: 2
jobs:
  build:
    docker:
      - image: node:11.14.0
        environment:
          PGHOST: localhost
          PGUSER: docker
          PGDATABASE: docker
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: docker
          POSTGRES_DB: corepg
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install postgres client
          command: sudo apt install -y postgresql-client
      - run:
          name: Run tests
          command: npm test
