version: 2
jobs:
  build:
    docker:
      - image: node:11.14.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
