-- Rename the old enum
ALTER TYPE moderation_action_type RENAME TO moderation_action_type__;
-- Create new enum
CREATE TYPE moderation_action_type AS ENUM (
  'adminBoards.updateCategories',
  'adminModerators.add',
  'adminModerators.remove',
  'adminReports.createMessageReportNote',
  'adminReports.updateMessageReportNote',
  'adminReports.createPostReportNote',
  'adminReports.updatePostReportNote',
  'adminReports.createUserReportNote',
  'adminReports.updateUserReportNote',
  'adminReports.updateMessageReport',
  'adminReports.updatePostReport',
  'adminReports.updateUserReport',
  'adminRoles.add',
  'adminRoles.remove',
  'adminRoles.update',
  'adminRoles.reprioritize',
  'adminSettings.update',
  'adminSettings.addToBlacklist',
  'adminSettings.updateBlacklist',
  'adminSettings.deleteFromBlacklist',
  'adminSettings.setTheme',
  'adminSettings.resetTheme',
  'adminUsers.update',
  'adminUsers.ban',
  'adminUsers.unban',
  'adminUsers.banFromBoards',
  'adminUsers.unbanFromBoards',
  'adminUsers.addRoles',
  'adminUsers.removeRoles',
  'boards.create',
  'boards.update',
  'boards.delete',
  'threads.title',
  'threads.sticky',
  'threads.createPoll',
  'threads.lock',
  'threads.move',
  'threads.lockPoll',
  'threads.purge',
  'threads.editPoll',
  'posts.update',
  'posts.undelete',
  'posts.delete',
  'posts.purge',
  'users.update',
  'users.delete',
  'users.reactivate',
  'users.deactivate',
  'conversations.delete',
  'messages.delete',
  'reports.createMessageReportNote',
  'reports.updateMessageReportNote',
  'reports.createPostReportNote',
  'reports.updatePostReportNote',
  'reports.createUserReportNote',
  'reports.updateUserReportNote',
  'reports.updateMessageReport',
  'reports.updatePostReport',
  'reports.updateUserReport',
  'bans.ban',
  'bans.unban',
  'bans.banFromBoards',
  'bans.unbanFromBoards',
  'bans.addAddresses',
  'bans.editAddress',
  'bans.deleteAddress'
);
-- Update table refrencing enum
ALTER TABLE moderation_log ALTER COLUMN action_type TYPE moderation_action_type USING action_type::text::moderation_action_type;

-- Drop the old enum
DROP type moderation_action_type__;

UPDATE moderation_log SET action_type = 'bans.ban' WHERE action_type = 'adminUsers.ban';
UPDATE moderation_log SET action_type = 'bans.unban' WHERE action_type = 'adminUsers.unban';
UPDATE moderation_log SET action_type = 'bans.banFromBoards' WHERE action_type = 'adminUsers.banFromBoards';
UPDATE moderation_log SET action_type = 'bans.unbanFromBoards' WHERE action_type = 'adminUsers.unbanFromBoards';

-- Rename the old enum
ALTER TYPE moderation_action_type RENAME TO moderation_action_type__;
-- Create new enum without adminUsers ban fields
CREATE TYPE moderation_action_type AS ENUM (
  'adminBoards.updateCategories',
  'adminModerators.add',
  'adminModerators.remove',
  'adminReports.createMessageReportNote',
  'adminReports.updateMessageReportNote',
  'adminReports.createPostReportNote',
  'adminReports.updatePostReportNote',
  'adminReports.createUserReportNote',
  'adminReports.updateUserReportNote',
  'adminReports.updateMessageReport',
  'adminReports.updatePostReport',
  'adminReports.updateUserReport',
  'adminRoles.add',
  'adminRoles.remove',
  'adminRoles.update',
  'adminRoles.reprioritize',
  'adminSettings.update',
  'adminSettings.addToBlacklist',
  'adminSettings.updateBlacklist',
  'adminSettings.deleteFromBlacklist',
  'adminSettings.setTheme',
  'adminSettings.resetTheme',
  'adminUsers.update',
  'adminUsers.addRoles',
  'adminUsers.removeRoles',
  'bans.ban',
  'bans.unban',
  'bans.banFromBoards',
  'bans.unbanFromBoards',
  'bans.addAddresses',
  'bans.editAddress',
  'bans.deleteAddress',
  'boards.create',
  'boards.update',
  'boards.delete',
  'threads.title',
  'threads.sticky',
  'threads.createPoll',
  'threads.lock',
  'threads.move',
  'threads.lockPoll',
  'threads.purge',
  'threads.editPoll',
  'posts.update',
  'posts.undelete',
  'posts.delete',
  'posts.purge',
  'users.update',
  'users.delete',
  'users.reactivate',
  'users.deactivate',
  'conversations.delete',
  'messages.delete',
  'reports.createMessageReportNote',
  'reports.updateMessageReportNote',
  'reports.createPostReportNote',
  'reports.updatePostReportNote',
  'reports.createUserReportNote',
  'reports.updateUserReportNote',
  'reports.updateMessageReport',
  'reports.updatePostReport',
  'reports.updateUserReport'
);
-- Update table refrencing enum
ALTER TABLE moderation_log ALTER COLUMN action_type TYPE moderation_action_type USING action_type::text::moderation_action_type;

-- Drop the old enum
DROP type moderation_action_type__;
